#!/usr/bin/php -q
<?php
set_time_limit(0);
error_reporting(E_ALL);
date_default_timezone_set('UTC');
require '/usr/lib/sysadmin/includes.php';
if (isset($argv[1])) {
    // Underp the base64
    $b = str_replace('_', '/', $argv[1]);
    $settings = @json_decode(gzuncompress(@base64_decode($b)), true);
    if (is_array($settings)) {
        $buid = $settings[0];
        $txn_id = $settings[1];
        $jobid = $settings[2];
        $location = $settings[3];
        $warm = $settings[4];
    }
  }
$command = '/usr/sbin/fwconsole backup --backup=' . escapeshellarg($buid) . '' . $warm . ' --transaction=' . escapeshellarg($jobid) . ' >> '.$location.'/backup_'.$jobid.'_out.log 2> '.$location.'/backup_'.$jobid.'_err.log & echo $!';
$message = $status = "";
exec($command);
sleep(1);
$fileNameLoc = '';
$f = fopen($location.'/backup_'.$jobid.'_out.log', 'r');
while (!feof($f)) {
    $line = fgets($f);
    if(strpos($line, 'File location:') !== false){
        $words = explode(" ",$line);
        foreach ($words as $value) {
            if(strpos($value, '.tar.gz') !== false){
                $fileNameLoc = $value;
                break;
            }
        }
    }
}
fclose($f);
if($fileNameLoc) {
    $status = 'Executed';
    $message = 'Backup Done';
    $output['backup_file'] = $fileNameLoc;
} else {
    $message = 'Backup Errored';
    $status = 'Failed';
    $output['backup_file'] = '';
}

$db = \Sysadmin\FreePBX::Database();
$sql = ("UPDATE IGNORE api_asynchronous_transaction_history SET event_status = :event_status , failure_reason =:failure_reason, process_end_time =:end_time, event_output =:event_ouput WHERE `txn_id` = :txn_id");
$sth = $db->prepare($sql);
$sth->execute([
    ":event_status" => $status,
    ":failure_reason" => $message,
    ":end_time" => time(),
    ":txn_id" => $txn_id,
    ":event_ouput" => json_encode($output)
]);

exit();
?>