#!/usr/bin/php -q
<?php
error_reporting(E_ALL);
date_default_timezone_set('UTC');
$commands = ['fwconsole util clearunuseddevices', 'fwconsole epm rebuild all'];
foreach ($commands as $command) {
    exec($command);
}

?>
